- name: Create replication user
  shell: sudo -u postgres psql -c "DROP ROLE IF EXISTS {{ replication_user }};CREATE ROLE {{ replication_user }} WITH REPLICATION LOGIN PASSWORD '{{ replication_password }}';"
  notify: Restart PostgreSQL
