- name: Stop PostgreSQL on replica
  systemd:
    name: postgresql
    state: stopped

- name: Clear existing data directory
  file:
    path: /var/lib/postgresql/{{ postgresql_version }}/main
    state: absent

- name: Create base backup
  command: >
    pg_basebackup -h {{ hostvars['primary']['ansible_host'] }} -D /var/lib/postgresql/{{ postgresql_version }}/main
    -U {{ replication_user }} -P -v --wal-method=stream
  become_user: postgres

- name: Configure replica for replication
  template:
    src: recovery.conf.j2
    dest: /var/lib/postgresql/{{ postgresql_version }}/main/recovery.conf
  notify: Restart PostgreSQL
