- name: Stop PostgreSQL on replica
  systemd:
    name: postgresql
    state: stopped

- name: Clear existing data directory
  file:
    path: /var/lib/postgresql/{{ postgresql_version }}/main/
    state: absent

- name: Configure .pgpass
  template:
    src: pgpass.j2
    dest: /var/lib/postgresql/.pgpass
    owner: postgres
    group: postgres
    mode: 0600
  notify: Restart PostgreSQL


- name: Create base backup
  shell: sudo -u postgres pg_basebackup -h {{ hostvars['primary']['ansible_host'] }} -D /var/lib/postgresql/{{ postgresql_version }}/main/
    -U {{ replication_user }} -P -v -R
  notify: Restart PostgreSQL
